### ISSUE TITLE
Native Crash

### ISSUE THREAD

**Issue by Lyzev** [Redstonecrafter0/MediaPlayerInfo#2]
**Describe the bug**
A crash occurs when changing the song during the session query.

**To Reproduce**
1. Request the sessions in Kotlin
2. Change song in Spotify
3. Crash!

**Expected behavior**
It should not crash. (Correct error handling)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.1.0

**Comment by Redstonecrafter0** [comment]
This should not happen. This should be resolved in 0.1.0-rc1. Please provide the commit hash for now since no version is released yet.

**Comment by Redstonecrafter0** [comment]
Could you please try the build from https://github.com/Redstonecrafter0/MediaPlayerInfo/actions/runs/9058793857

**Comment by Lyzev** [comment]
Still crashing, not fixed.
@Redstonecrafter0 

**Stacktrace:**
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  dev.redstones.mediaplayerinfo.impl.win.WindowsMediaPlayerInfo.getMediaSessions()Ljava/util/List;+0
j  dev.redstones.mediaplayerinfo.MediaPlayerInfo$Instance.getMediaSessions()Ljava/util/List;+4
...
```
